# Generated by Django 4.2.7 on 2023-11-30 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turbo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='user_view_count',
            field=models.IntegerField(blank=True, null=True, verbose_name=django.db.models.deletion.SET_NULL),
        ),
    ]
